

INPUT_TYPE = "xml"
WORD_MARKER = "w"
SECTION_MARKER = "line"
NORMALIZE = False

DEFAULT_LANGUAGE = "english"
LANGUAGES = ["latin","french"]
RESOURCEDIR = "../resources/"

MIN_CONFIDENCE = 0.6
MAX_NOISE = 1
MIN_SEQUENCE = 5
LOGPROB_THRESHOLD = 2
